### ISSUE TITLE
Unknown_meta folder causing image deletion and not saving new images

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#12]
I had a weird issue tonight so not sure what you need me to upload. I reran a few usernames tonight that were previously run a few weeks ago so the files weren't in folders based off the models. 

I checked one of the folders only to find the only thing in there was a folder called unknown_meta. Neither the main folder of the username or the unknown_meta folder contained any new or previously downloaded images. The window even shows that files were being downloaded, but I have been unable to locate them.  

I copied the same user over to a new folder with the existing images and ran it again. The same thing happened. Images are gone and Unknown_Meta folder is created. Again it also told me it downloaded 14 images and I have none. 

When I tested on my NAS, I found the images in the recycle bin, but in Windows they are just gone so it must be permanently deleting them after it thinks they have been moved. I don't know if this affected all users or only certain ones. Two users for sure that were affected were linkin911 and beg0n, linkin911 was the one I tested on windows and my NAS. Checking other users though they have unknown_meta folders which only contain the meta txt files and no images. 

I don't know if the bug was introduced in this latest version or the one just before it trying to fix the folder bug. 

In looking into this a bit further it looks like any user that ends up with an unknown_meta folder won't have any images saved in that folder. 

On a side note, I am guessing once fixed I will need to nuke my  downloaded_images json or at least wipe anything in the last 48 hours since it thinks those images were downloaded even though they are now gone.

**Comment by Confuzu** [comment]
fixed it 
There is a new category invalid meta when the script cannot use the data from the metadata files to create folders.

**Comment by Nobrumski** [comment]
Thanks I appreciate it. Is wiping some of the downloaded_images json results in the last 24-48 hours the best bet or should I just start with a clean json with all the changes?

**Comment by Confuzu** [comment]
simply delete the entries for the last 24 to 48 hours and it should work.

**Comment by Nobrumski** [comment]
Thanks. I think actually I am just going to have to start a fresh json the more I think about it. The last 48 hours would address the new images that didn't get saved, but the original images from prior won't redownload. I can't think of a good way to have the json compare against local files to see if those files are still there.
