### ISSUE TITLE
Enhancement - create download folders in mode folders

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#14]
It would be nice if Image Grabber could separate the users, model number, and model tag search into their own subfolders based off the mode even if just using users, model number, and model tag as the folder name. 

Currently I move the folders myself at the end of the night otherwise the image download folder can get unwieldy especially when trying to figure out is it a username or a model tag at a glance.

**Comment by Confuzu** [comment]
I have implemented your idea. give it a try
