### ISSUE TITLE
Bug - The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#15]
I had another windows character error tonight. 

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'image_downloads\\duskfallcrew\\FFINSPOMIX.fp16 x (1-alpha-beta) + HellaineIllustrationPonyXLV2Cross.fp16 x alpha + HellaineIllustrationPonyXL.fp16 x beta (alpha = 0.0 1.0 0.995722430686905 0.982962913144534 0.961939766255643 0.933012701892219 0.896676670145617 0.853553390593274 0.80438071450436 0.75 0.5 0.434736903889974 0.37059047744874 0.308658283817455 0.25 0.195619285495639 0.146446609406726 0.103323329854382 0.0669872981077805 0.0380602337443566 0 beta = 0.0 1.0 0.995722430686905 0.982962913144534 0.961939766255643 0.933012701892219 0.896676670145617 0.853553390593274 0.80438071450436 0.75 0.5 0.434736903889974 0.37059047744874 0.308658283817455 0.25 0.195619285495639 0.146446609406726 0.103323329854382 0.0669872981077805 0.0380602337443566 0)_cosineA ID 1'

[2024-04-06 040520,806 - ERROR.txt](https://github.com/Confuzu/CivitAI_Image_grabber/files/14892929/2024-04-06.040520.806.-.ERROR.txt)

**Comment by Nobrumski** [comment]
I had another one tonight for a different user and folder.

2024-04-07 02:10:53,276 - ERROR - An unexpected error occurred: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'image_downloads\\VeryDumb\\Perfect World [\x7fN\x16uL_perfectWorld_v4Baked'
Traceback (most recent call last):
  File "X:\CivitAI_Image_grabber-main\civit_image_downloader.py", line 621, in main
    results = await asyncio.gather(*tasks)
  File "X:\CivitAI_Image_grabber-main\civit_image_downloader.py", line 541, in download_images
    sort_images_by_model_name(dir_name)
  File "X:\CivitAI_Image_grabber-main\civit_image_downloader.py", line 224, in sort_images_by_model_name
    os.makedirs(target_dir, exist_ok=True)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'image_downloads\\VeryDumb\\Perfect World [\x7fN\x16uL_perfectWorld_v4Baked'

**Comment by Confuzu** [comment]
i have looked at the bugs and updated my code so that they do not reappear.

**Comment by Nobrumski** [comment]
Thanks for the quick fix. I am seeing some oddities with the update though. Not sure why it randomly changed languages from english, but also 

Fehler beim Kopieren der Datei image_downloads\duskfallcrew\426566.png nach image_downloads\duskfallcrew\0.6(animeBackgrounds_10) + 0.4(cheeseDaddys_35) + 0.45(cheeseDaddys_35 - wave...\426566.png. Fehler: [Errno 2] No such file or directory: 'image_downloads\\duskfallcrew\\0.6(animeBackgrounds_10) + 0.4(cheeseDaddys_35) + 0.45(cheeseDaddys_35 - wave...\\426566.png'
Fehler beim Kopieren der Datei image_downloads\duskfallcrew\6309630.png nach image_downloads\duskfallcrew\PoltergeistMix-SDXL.fp16 x 0.0 + Poltergeist1pt2bck.fp16 x 0.5 + ComicXLBackM...\6309630.png. Fehler: [Errno 2] No such file or directory: 'image_downloads\\duskfallcrew\\PoltergeistMix-SDXL.fp16 x 0.0 + Poltergeist1pt2bck.fp16 x 0.5 + ComicXLBackM...\\6309630.png'
Fehler beim Kopieren der Datei image_downloads\duskfallcrew\8355232.png nach image_downloads\duskfallcrew\FFINSPOMIX.fp16 x (1-alpha-beta) + HellaineIllustrationPonyXLV2Cross.fp16 x a...\8355232.png. Fehler: [Errno 2] No such file or directory: 'image_downloads\\duskfallcrew\\FFINSPOMIX.fp16 x (1-alpha-beta) + HellaineIllustrationPonyXLV2Cross.fp16 x a...\\8355232.png'

I am also seeing those folders in the download, but nothing saved in them. Guessing maybe they are shortened so it can't find them. 
X:\CivitAI_Image_grabber-main\image_downloads\duskfallcrew\0.4(0.45(0.5(epicMixAnimeNSFW_v4) + 0.5(comiNoirV2_comiNoirV2)) + 0.55(icomix

**Comment by Confuzu** [comment]
check  again

**Comment by Nobrumski** [comment]
I am not seeing the errors, but it seems to only grab 100 images now and stop so tough to tell. I tried it twice in a row and both times exactly 100.  I used duskfallcrew and VeryDumb. Dusk has 11k+ and I have nowhere near that so it should still find more than that.

**Comment by Nobrumski** [comment]
Still seems to have an issue. Reran it again on dusk and says it downloaded, but nothing saved again in the folder. I found them in the recycle bin again on my nas.

**Comment by Confuzu** [comment]
i have no problems with  this version to  download VeryDumb & duskfallcrew. 
Remember the script can only download what the API outputs.  
The api output of duskfallcrew is 9  Pages a 100 Images Number of downloaded images: 858
Ther API  Output of VeryDumb is 21 Pages a 100 Images  Number of downloaded images: 2100 

Both  with the new nsfw=X parameter to  get all  images

**Comment by Nobrumski** [comment]
Thanks, I should have started with an empty directory so I could truly verify. Maybe the folders were just leftover, but when I searched for the image by name from the cmd window it didn't find it. 

If it is easy to add, would it be possible to have the end image summary break it down by username,tag, or number? I usually run a couple at a time and the count is nice, but no way to know is that all that broke down by request. If not no biggie. Also let me know if you have a lo-fi or Patreon or something. Happy to throw you a donation for your work here.

**Comment by Confuzu** [comment]
i  updated my Profile with my ko-fi link from another project
