### ISSUE TITLE
limit at 999 images

### ISSUE THREAD

**Issue by dynatron832** [Confuzu/CivitAI_Image_grabber#17]
i tryed to download the images of a user. civit say´s it should be 2k. but the downloader stops at 999 and is done. it also refuses to go if i start the downloader again with the same settings.

**Comment by Confuzu** [comment]
The numbers on the CivitAI Webpage and the Civit AI API from where the scripts gets the images can sometimes different. That is not a problem of the script. 

The script will check for images already downloaded when you run the same Username or Model ID and skips already downloaded Images.

The newest update has an option that allows the tracking file to be switched off.

**Comment by dynatron832** [comment]
but it looks like it is not downloading all. if i open the userpage and the pics it show´s me the newest pics of the user. but none of them are under the downloaded pic´s.

i had old links to pictures of the user. and so i can confirm the script starts with the oldest and getting the newer ones. but not even all. only 999.

[https://civitai.com/user/iJWiTGS8](https://civitai.com/user/iJWiTGS8)

**Comment by Confuzu** [comment]
Thanks for the username link.  I  looked into  it and the API  gives only links to 999  Images back. 
Sorry, but this is a problem of CivitAI that their public API does not include all images. The script can only download the images that the API provides. 
The script has already taken into account the new filter that civitAI has installed regarding NSFW.

**Comment by dynatron832** [comment]
whats with the collections/post´s id´s ? why not downloading with them ?

**Comment by Confuzu** [comment]
the Postid query function in the API  is partly not working  no  matter what  ID is use i  get always the same results.  When i  use an ID and sort for newest i  get again all images not only the images from the post ID
