### ISSUE TITLE
Failed identifiers: Username randomly happening even though valid users

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#19]
Not sure if they did something with the API or if it is spitting out an error similar, but I have had a few users that will randomly reject like it is not a valid username when run with other usernames. 

ClamJam and DarkAgent was one. When run individually they complete fine, but when running together they were acting like either were known users.

Currently happening with albertolologgb627 and Aishavingfun. No traceback errors so not sure the API is actually rejecting with. Originally ran these 2 with 2 others that completed successfully but rejected these 2. Running just the two names, the first succeeded, but second failed. 
Number of downloaded images: 507
Number of skipped images: 0
Failed identifiers:
username: albertolologgb627
Image download completed.

By itself Aishavingfun failed, but rerunning re-download worked. Not sure if it is a json issue, though albertolologgb627 worked without re-download enabled when I ran just the two. 

I noticed a trend with this. It always seems to be the first name of multiple names that fails if it is going to fail.

**Comment by Confuzu** [comment]
clamjam,DarkAgent works fine alone and together, also  no problems with  Aishavingfun,albertolologgb627 alone or together.
