### ISSUE TITLE
Enhancement - Ability to use both Model ID and Version ID to filter images

### ISSUE THREAD

**Issue by jpummill** [Confuzu/CivitAI_Image_grabber#22]
Many models provide multiple versions, each of which can include thousands of pictures.

It would be helpful to have the ability to filter down to a single Version ID to be more focused and avoid downloading gigabytes of data for versions that were not of interest.  Would probably make CivitAI happier as well.

**Comment by Confuzu** [comment]
Really good idea. I  will  look into  it and  try to figure out how to  code it.

**Comment by Confuzu** [comment]
Please take a look for the update

**Comment by jpummill** [comment]
Thank you.  Seems to work perfectly.

A couple observations:
1)  I would have thought that you needed both Model ID and Version ID but that doesn't appear to be the case as you don't ask for the Model ID when searching by Version ID.
2)  Even though my test downloaded the correct number of images while testing a single Version ID.  It created multiple sub-directories to store the images which I didn't understand.

**Comment by Confuzu** [comment]
1. The model version ID is sufficient for the API query. This means that you can now even download images, e.g. from Loras or embeddings, individually. No more need to download entire model image galleries. 

2.  the sub-directories are created based on the model with which the image was created. The name of the folder is read from the API response and created based on the model name.  The data in the txt file is also read from the API response and written in. If no meta data is available, a link for civitai.com where the image can be found is generated and written to the txt file.  

Hope that  answers you questions
