### ISSUE TITLE
Ability to Prefill Prompts

### ISSUE THREAD

**Issue by earthyrock** [Confuzu/CivitAI_Image_grabber#25]
Not really an issue so much as a request. Thanks in advance for considering my request, and btw, **much appreciate your app**!

Is there a way I can modify the **civit_image_downloader.py** to accept prefilled values, i.e. a stripped out version of your file where the choices are pre-filled values rather than prompts. I tried doing this manually and failed miserably.

My needs are not often going to change, so this would be a huge boon.

Example:
```
      Enter timeout value (in seconds): **60** or **default**
      Choose image quality (1 for SD, 2 for HD): **2**
      Allow re-downloading of images already tracked (1 for Yes, 2 for No) [default: 2]: **2** or **default** 
      Choose mode (1 for username, 2 for model ID, 3 for Model tag search, 4 for model version ID): **1**
      Mode 3 
      Enter tags (comma-separated): **TAG (I'll fill this in manually)**
      Disable prompt check? (y/n): **y**
```

Even better for my purposes if there was a way to pipe these values at app start.

Examples
```
python civit_image_downloader.py 60,2,2,1,TAG,y
```
or
```
python civit_image_downloader.py --timeout=60 --quality=2 --redownload=2 --mode=1 --tags=TAG --disable_prompt_check=y
```

**Comment by Confuzu** [comment]
i  Build in Command-Line Parameter Support,  please update and read the 1.2 New Feature & Update for more infos

**Comment by earthyrock** [comment]
GREAT JOB! You're fantastic!!! Much KUDOS!!! ;)

**Comment by earthyrock** [comment]
GREAT JOB! You're fantastic!!! Much KUDOS!!! ;)
