### ISSUE TITLE
Only downloads 100 images

### ISSUE THREAD

**Issue by LesPles** [Confuzu/CivitAI_Image_grabber#3]
Used to work fine so I suspect a change on civitai, but now when attempting to download all a users images, only 100 are downloaded before your script says "Image download completed successfully".

Example user:  WTFusion   (via **https://civitai.com/user/WTFusion/images**) has 1860 images at time of writing, only 100 are downloaded.

**Comment by Confuzu** [comment]
It is and API issue from civit AI.  I opened a bug report for this

**Comment by sambaspo** [comment]
Hi Confuzu, thank you a lot for your incredible work. I used your script for almost 2 months before it showed the 100 image limit problems. It was incredibily useful and it was the only one script of this kind here on github. All of the other hosted projects focused on downloading models and a bunch of sample images from civitai but your's one allowed users to download entire galleries...and collecting thousand of prompts in an incredibly effective and fast way.I really hope you will have time to fix it sooner or later. I don't understand anything about python or the specs of the civitai api but could the limit depend from a recent api update that requests the user api key to overcome the limit?

**Comment by Confuzu** [comment]
I've looked again to see what I can do. I wrote a workaround but that only helps to a very limited extent. 
With the workaround version you get about 200 or maybe 300 but then you get an error message and the API blocks all further attempts.  

The script will stop with  "Too many requests. Stopping the download process."

The problem is on the side of civitAi because their API is buggy.

**Comment by Confuzu** [comment]
The API is Fixed the script is working again

**Comment by Confuzu** [comment]
> Hi Confuzu, thank you a lot for your incredible work. I used your script for almost 2 months before it showed the 100 image limit problems. It was incredibily useful and it was the only one script of this kind here on github. All of the other hosted projects focused on downloading models and a bunch of sample images from civitai but your's one allowed users to download entire galleries...and collecting thousand of prompts in an incredibly effective and fast way.I really hope you will have time to fix it sooner or later. I don't understand anything about python or the specs of the civitai api but could the limit depend from a recent api update that requests the user api key to overcome the limit?


API is Fixed script is working again
