### ISSUE TITLE
Unable to download from CivitAi, did they change their API?

### ISSUE THREAD

**Issue by chard101** [Confuzu/CivitAI_Image_grabber#31]
Was downloading a user gallery a few hours ago.  Noticed the CivitAI site when into a "maintenance mod" for around 30 minutes.  I was not able to browse the site (got the maintenance page" and my download stopped.

I've tried to restart the download again and I've tried a new user profile to download, the output I get is:

```
Running in interactive mode.
Enter timeout value (in seconds): 60
Choose image quality (1 for SD, 2 for HD): 2
Allow re-downloading of images already tracked (1 for Yes, 2 for No) [default: 2]: 2
Choose mode (1 for username, 2 for model ID, 3 for Model tag search, 4 for model version ID): 1
Enter username: TARGAT_USERNAME
Total API items: 0, Total downloaded: 0

Number of downloaded images: 0
Number of skipped images: 0
```

As anyone else getting this or is it just me?

**Comment by Confuzu** [comment]
That username you tried to download does not exist. I  tried  another one CBIE919 and i  got all the pics from that username

**Comment by chard101** [comment]
I think my install got corrupted, have started with a fresh directory and all is good.

Thank you for taking the time to look and thank you again for sharing a great tool.

Much appreciated.
