### ISSUE TITLE
API changes possibly affecting image grabbing

### ISSUE THREAD

**Issue by Nobrumski** [Confuzu/CivitAI_Image_grabber#9]
With the new content rating system, they rolled out changes to image ratings. This looks like it might be affecting the grabber now. 

Using the new version you just uploaded, I tried user Superspice and nothing was grabbed.  I tried mnh which grabbed 7 of his 33 images. Nothing reported as to why it stopped. The 7 images are all PG that were grabbed. 

I did find this on their discord which was a few days ago so not sure if they have since updated the API to use the rating numbers over True/False.

hi all, does anyone know what the the new public API "nsfwLevel": 1, numbers mean?

I saw that CivitAI now has "PG", "PG-13", "R", "X" and "XXX" for NSFW filters, but I'm wondering what number corelates to what value in the public API, does anyone know? 

PG = 1
PG13 = 2
R = 4
X = 8
XXX = 16
confirmed, sorry about that
I believe that the public api is currently using the nsfw: true/false to return either pg/pg13 images or R+

**Comment by Confuzu** [comment]
The Civit AI  API Reference says Filter to images that contain mature content flags or not (undefined returns all) but they changed it but no  change in the Reference. 
It was quite easy to fix.  Now the download of images from users with R rated content works again. I tried it with Superspice and it works again.
